#!/usr/bin/env python

from __future__ import annotations

import argparse
from pathlib import Path

import yaml


DEFAULT_REMOVALS = {"h5py", "memory_profiler", "pytest", "pytest-xdist"}


def package_name(spec: str) -> str:
    for sep in (" ", "=", "<", ">", "!"):
        spec = spec.split(sep, 1)[0]
    return spec.strip()


def main() -> None:
    parser = argparse.ArgumentParser(description="Trim and augment a Psi4 conda env spec for wheel builds.")
    parser.add_argument("env_file", help="Path to env yaml generated by psi4-path-advisor.")
    parser.add_argument(
        "--add",
        action="append",
        default=[],
        help="Dependency spec to append if missing. May be passed multiple times.",
    )
    parser.add_argument(
        "--remove",
        action="append",
        default=[],
        help="Package name to remove in addition to the default test-only set.",
    )
    args = parser.parse_args()

    env_path = Path(args.env_file).resolve()
    data = yaml.safe_load(env_path.read_text(encoding="utf-8"))
    dependencies = data.get("dependencies", [])

    removals = DEFAULT_REMOVALS | set(args.remove)
    filtered = [item for item in dependencies if package_name(str(item)) not in removals]
    present = {package_name(str(item)) for item in filtered}

    for spec in args.add:
        if package_name(spec) not in present:
            filtered.append(spec)
            present.add(package_name(spec))

    data["dependencies"] = filtered
    env_path.write_text(yaml.safe_dump(data, sort_keys=False), encoding="utf-8")


if __name__ == "__main__":
    main()
